// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config"; // Carrega variáveis de ambiente do arquivo .env
import { defineConfig } from "prisma/config"; // Importa a função defineConfig do Prisma

// Exporta a configuração do Prisma usando defineConfig
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
